[build]
  base = "/"
  publish = "build/"
  command = "middleman build --verbose && cp netlify_headers build/_headers"
  environment = { NODE_VERSION = "16.19.0" }

[context.production]
  command = "middleman build --verbose"
  environment = { NODE_VERSION = "16.19.0" }

[[redirects]]
  from = "/"
  to = "/20170710"
  status = 302

[[redirects]]
  from = "https://wanikani-api-docs.netlify.com/*"
  to = "https://docs.ap.wanikani.com/:splat"
  status = 301

[[redirects]]
  from = "http://wanikani-api-docs.netlify.com/*"
  to = "http://docs.ap.wanikani.com/:splat"
  status = 301
